services:
  postgres:
    image: postgres:14
    container_name: ai-chat-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: ai-chat-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-chat-project
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env
    # 如果你不想每次都 build，也可以采用直接引用镜像的方式
    # image: node:18
    # 可选：挂载代码以支持热重载（仅开发环境）
    volumes:
      - .:/app
      - /app/node_modules
    # 可选：设置工作目录
    working_dir: /app

volumes:
  db_data:
